language: node_js
node_js:
- 12
git:
  depth: false
# install:
#   - ./integration/js/script/install-kite
#  - pip install --user awscli
script: script/prevent-multiple-pr-commits && npm run test:retry # && npm run test:integration
addons:
  sauce_connect:
    username: "chimesdk"
    no_ssl_bump_domains: all
  jwt:
    secure: "Fs/jNys/0BYYFRLlHBWYWulAE4ydGp80f3eS1oewfUc6vYBo2+SGWyvchaattMn/5CoVdgIsrwj0A4OGXB2FJfkgiCENZ9LE+XVG1JWJIKPIe88VYrILVqsnPay9lTR7myVUUoDdtHDa+pO4h22BeEaIeJQGhmX5m8lVkjYdtVk76f0aW9SoN9sKNLQVARROvkqebMmFlzYuvbFkvmDohrz+alnAfrP/FFPdE9qN8ERm8G00qsOxLq3uxhJHadbKqG2aSOrhY+cyMJAXoDjojPVsWn1/0OUE4NXut6HLQXZJnq5m1Dw5U2DUOi4M/wcdaiWM6YM64HMPo4UchffSX4Tx8zdXfzhjnUjRYaHx3GMP2PK9HzFmnrOCuHsItly1/CaxlqOXnwEp4+YXGmdL7UR4HBxWcdJBDugPyfobIfusbC4aIVSoXrdt5HB2kPMmOdvRCnUJOFVHBVk3RMLQxhK5rFU3KlMsE3t4mOodY6kKkP9dihyuL3UyhCb/0g35cXBkJHTy16vYMWsx4rT4STmI0O+bGGPcNWpPvNUecDcxA0aVDrJTfpqzIGn9TPvhp7r2pV6nahu/mikjMSV6sYrtA66Vgsw+ddPgjXQPhPrREQrp6WOM9Ui16eRUPTTCS6pEU7N66TJN6dM08J1B5uFqWhIWdeOHkAwp/s5NhA0="
  browserstack:
    username: "chimesdk"
    access_key:
      secure: "TRGKE6oqaCXAhYcLVu6bu1iH/IvtAIj2cKx7o73ukrOm9ifUfmpAzfVFlQB8evCQM67SP8u2x4QyaWhD+JHZKjUkj/DkY6XjJPyT6VjOhqiZQYU+GGDVI3xwawmap3rWUIW4Gdo2lK4NfTGU1Z+gwVLAmIuNXjgFhaWE93/0ycSS3B4bKUqlGJX/YYZVcpbTnQqS6SOiqt6XJMHiBqIU8+r63RuJcBifrccQbJYz5g5ufQpVagyOScTKKdm8T93vHXp12A3XkMf2W911Ef06XOVRmG/gKET9/FBnM12F6430vDGx8kYeKbo9E7YpRlJS8M6QtO7hpEGfZlZItPWb2cP+tp+W+JRgdnhlO8nSXvhy6RH2iwhLQRP4/B1AOPybab405H0MD+p45jklmkhNw4iY9LXdI9/u3Sd8DuVIkq/bNblVIFKuqw0BFNi5PXgPfizenc3AfPThGJLIUAVUzXte+niF1sajwUB/l3ob0rlg0Nhk1OnsVR6CingN8uzXYo9DAnEzbRgJOazJYASVp5WTP8i4v+9+tMndz3NT1g66FbcY9rFmCTesqMQ7xTjKTIr5/e32wOo67dgolC2orp22tsDmWYtmHZ89NqOmuxFMH3j1oMFCx9tB5aYLth2YTsbe6Iac5d3sND/wbcTZJDEgdpeGqUfmHy3OsM5DHIU="